export default {
  mnemonic: '',
  wallet: null,
  walletId: null,
  wordsNumbersAllowed: [9, 12, 15, 18, 21, 24],
  network: NaN,
  walletName: NaN,
  assetName: NaN,
  tokenAmount: NaN,
  passphrase: NaN,
  metadata: NaN,
  transaction: null,
  addresses: null,
  isValidAdress: false,
  isSendingAda: false,
  isValidAmount: false,
  amount: 0,
  amountFromatted: '0.000000',
  total: 0,
  totalFormatted: '0.000000',
  fee: 0,
  feeFormatted: '0.000000',
  sendAll: false,
  metadataFile:''
};
