name: draft-pr-releases
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-artifacts:
    name: Build release artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        #  - ubuntu-latest
        #  - macos-latest
          - windows-latest
        node_version:
          - 14
        architecture:
          - x64
    steps:
    - uses: actions/checkout@v2
    - name: Make git short-commit/pr-number available to different steps
      id: metadata
      run: |
        echo "::set-output name=COMMIT::$(echo ${GITHUB_SHA} | head -c7)"
        echo "::set-output name=PR_NUMBER::$(echo ${GITHUB_REF} | awk -F/ '{print $3}')"
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
        architecture: ${{ matrix.architecture }}
    - name: Build artifacts for ${{ matrix.os }}-${{ matrix.architecture }}
      env:
        MATRIX_OS: ${{ matrix.os }}
        RELEASE_TAG: "PR-${{ steps.metadata.outputs.PR_NUMBER }}"
      shell: bash
      run: |
        pwd
        which bash
        export PATH=${PATH}:$(dirname $(which bash))
        npm i
        case "${MATRIX_OS}" in
          ubuntu*) PLATFORM=linux;;
          macos*) PLATFORM=macos;;
          windows*) PLATFORM=windows;;
        esac
        npm run binaries:${PLATFORM}
        npm run electron:build
        mkdir -p release-files
        ( ls dist_electron/*AppImage && cp -a dist_electron/*AppImage release-files/lift-wallet-${PLATFORM}-${RELEASE_TAG}.AppImage )
        ( ls dist_electron/*dmg && cp -a dist_electron/*dmg release-files/lift-wallet-${PLATFORM}-${RELEASE_TAG}.dmg )
        ( ls dist_electron/*exe && cp -a dist_electron/*exe release-files/lift-wallet-${PLATFORM}-${RELEASE_TAG}.exe )
    - name: Upload built artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-files
        path: release-files
        retention-days: 7

  draft-release:
    name: Draft release artifacts
    runs-on: ubuntu-latest
    needs: [build-artifacts]
    steps:
    - uses: actions/checkout@v2
    - name: Make git short-commit/pr-number available to different steps
      id: metadata
      run: |
        echo "::set-output name=COMMIT::$(echo ${GITHUB_SHA} | head -c7)"
        echo "::set-output name=PR_NUMBER::$(echo ${GITHUB_REF} | awk -F/ '{print $3}')"
    - name: Download release artifacts
      uses: actions/download-artifact@v2
      with:
        name: release-files
        path: release-files
    - name: Release PR draft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: "pull-request-${{ steps.metadata.outputs.PR_NUMBER }}"
        RELEASE_NAME: "Release PR#${{ steps.metadata.outputs.PR_NUMBER }}-${{ steps.metadata.outputs.COMMIT }}"
        RELEASE_NOTES: "Automatic release from GH action on this project."
      run: |
        sudo apt install -y npm tree
        sudo npm install -g publish-release
        set -x
        GITHUB_OWNER=$(echo ${GITHUB_REPOSITORY} | awk -F/ '{print $1}')
        GITHUB_REPO=$(echo ${GITHUB_REPOSITORY} | awk -F/ '{print $2}')
        git tag ${RELEASE_TAG}
        echo '{}' > package.json
        publish-release \
          --draft \
          --reuseRelease \
          --reuseDraftOnly \
          --tag ${RELEASE_TAG} \
          --owner ${GITHUB_OWNER} \
          --repo ${GITHUB_REPO} \
          --token ${GITHUB_TOKEN} \
          --name "${RELEASE_NAME}" \
          --notes "${RELEASE_NOTES}" \
          --assets $(ls release-files/* | xargs echo | sed 's| |,|g')

