name: draft-pr-releases
on:
  pull_request:
    types: [open, synchronize]

env:
  BUILD_DOCKER_IMAGE: node:14

jobs:
  build-linux:
    name: Build linux release artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make git short-commit/pr-number available to different steps
      id: metadata
      run: |
        echo "::set-output name=commit::$(echo ${GITHUB_SHA} | head -c7)"
        echo "::set-output name=pr_number::$(echo $GITHUB_REF | awk -F/ '{print $3}')"
    - name: Build
      env:
        PLATFORM: linux
        RELEASE_TAG: "pr-${{ steps.metadata.outputs.pr_number }}"
      run: |
        pwd
        ls -hal
        git status -sb
        mkdir release-files
        docker run -i --rm \
          -v ${PWD}:/src \
          -w /src \
          --entrypoint bash \
          ${BUILD_DOCKER_IMAGE} \
          -c "npm i && npm run binaries:${PLATFORM} && npm run electron:build"
        cp -a dist_electron/*AppImage release-files/lift-wallet-${PLATFORM}-${RELEASE_TAG}.AppImage

  build-macos:
    name: Build macos release artifacts
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make git short-commit/pr-number available to different steps
      id: metadata
      run: |
        echo "::set-output name=commit::$(echo ${GITHUB_SHA} | head -c7)"
        echo "::set-output name=pr_number::$(echo $GITHUB_REF | awk -F/ '{print $3}')"
    - name: Install docker
      run: |
        brew install docker-machine docker
        sudo docker --version
    - name: Build
      env:
        PLATFORM: macos
        RELEASE_TAG: "pr-${{ steps.metadata.outputs.pr_number }}"
      run: |
        pwd
        ls -hal
        git status -sb
        mkdir -p release-files
        docker run -i --rm \
          -v ${PWD}:/src \
          -w /src \
          --entrypoint bash \
          ${BUILD_DOCKER_IMAGE} \
          -c "npm i && npm run binaries:${PLATFORM} && npm run electron:build"
        done
        cp -a dist_electron/*dmg release-files/lift-wallet-${PLATFORM}-${RELEASE_TAG}.dmg

  draft-release:
    name: Draft release artifacts
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    steps:
    - uses: actions/checkout@v2
    - name: Make git short-commit/pr-number available to different steps
      id: metadata
      run: |
        echo "::set-output name=commit::$(echo ${GITHUB_SHA} | head -c7)"
        echo "::set-output name=pr_number::$(echo $GITHUB_REF | awk -F/ '{print $3}')"
    - name: Release PR draft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: "pull-request-${{ steps.metadata.outputs.pr_number }}"
        RELEASE_NAME: "Release ${{ steps.metadata.outputs.pr_number }}-${{ steps.metadata.outputs.commit }}"
        RELEASE_NOTES: "Automatic release from GH action on this project."
      run: |
        sudo apt install -y npm
        sudo npm install -g publish-release
        set -x
        GITHUB_OWNER=$(echo ${GITHUB_REPOSITORY} | awk -F/ '{print $1}')
        GITHUB_REPO=$(echo ${GITHUB_REPOSITORY} | awk -F/ '{print $2}')
        git tag ${RELEASE_TAG}
        echo '{}' > package.json
        publish-release \
          --draft \
          --reuseRelease \
          --reuseDraftOnly \
          --tag ${RELEASE_TAG} \
          --owner ${GITHUB_OWNER} \
          --repo ${GITHUB_REPO} \
          --token ${GITHUB_TOKEN} \
          --name "${RELEASE_NAME}" \
          --notes "${RELEASE_NOTES}" \
          --assets $(ls release-files/* | xargs echo | sed 's| |,|g')
